version: '3.9'

services:
  app:
    build: .
    container_name: express-mongoose-boilerplate
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    stop_signal: SIGINT
    command: ["npm", "start"]