# List all todos
GET http://localhost:3000/todos HTTP/1.1

###

# Create a todo
POST http://localhost:3000/todos HTTP/1.1
Content-Type: application/json

{
  "text": "Buy groceries"
}


###

# Get a todo
GET http://localhost:3000/todos/66b77b57aaedb3a2427029d4 HTTP/1.1


###

# Update a todo
PUT http://localhost:3000/todos/66b77b57aaedb3a2427029d4 HTTP/1.1
Content-Type: application/json

{
  "text": "Buy groceries 2"
}

###

# Delete a todo
DELETE http://localhost:3000/todos/66b77b98aaedb3a2427029d9 HTTP/1.1
